// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="qwen_superblock_qwen_superblock,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=6533154,HLS_SYN_TPT=3269598,HLS_SYN_MEM=134,HLS_SYN_DSP=0,HLS_SYN_FF=26736,HLS_SYN_LUT=81073,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module qwen_superblock (
        ap_clk,
        ap_rst_n,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        M,
        N_W1,
        N_W2,
        K
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM0_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM0_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM0_USER_VALUE = 0;
parameter    C_M_AXI_GMEM0_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM0_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM1_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM1_USER_VALUE = 0;
parameter    C_M_AXI_GMEM1_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM1_CACHE_VALUE = 3;
parameter    C_M_AXI_GMEM2_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM2_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM2_USER_VALUE = 0;
parameter    C_M_AXI_GMEM2_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM0_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM2_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_AWADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_AWID;
output  [7:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [C_M_AXI_GMEM0_AWUSER_WIDTH - 1:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_WDATA;
output  [C_M_AXI_GMEM0_WSTRB_WIDTH - 1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_WID;
output  [C_M_AXI_GMEM0_WUSER_WIDTH - 1:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [C_M_AXI_GMEM0_ADDR_WIDTH - 1:0] m_axi_gmem0_ARADDR;
output  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_ARID;
output  [7:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [C_M_AXI_GMEM0_ARUSER_WIDTH - 1:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [C_M_AXI_GMEM0_DATA_WIDTH - 1:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_RID;
input  [C_M_AXI_GMEM0_RUSER_WIDTH - 1:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [C_M_AXI_GMEM0_ID_WIDTH - 1:0] m_axi_gmem0_BID;
input  [C_M_AXI_GMEM0_BUSER_WIDTH - 1:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_AWADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_AWID;
output  [7:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [C_M_AXI_GMEM1_AWUSER_WIDTH - 1:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_WDATA;
output  [C_M_AXI_GMEM1_WSTRB_WIDTH - 1:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_WID;
output  [C_M_AXI_GMEM1_WUSER_WIDTH - 1:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [C_M_AXI_GMEM1_ADDR_WIDTH - 1:0] m_axi_gmem1_ARADDR;
output  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_ARID;
output  [7:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [C_M_AXI_GMEM1_ARUSER_WIDTH - 1:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [C_M_AXI_GMEM1_DATA_WIDTH - 1:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_RID;
input  [C_M_AXI_GMEM1_RUSER_WIDTH - 1:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [C_M_AXI_GMEM1_ID_WIDTH - 1:0] m_axi_gmem1_BID;
input  [C_M_AXI_GMEM1_BUSER_WIDTH - 1:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_AWADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_AWID;
output  [7:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [C_M_AXI_GMEM2_AWUSER_WIDTH - 1:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_WDATA;
output  [C_M_AXI_GMEM2_WSTRB_WIDTH - 1:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_WID;
output  [C_M_AXI_GMEM2_WUSER_WIDTH - 1:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [C_M_AXI_GMEM2_ADDR_WIDTH - 1:0] m_axi_gmem2_ARADDR;
output  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_ARID;
output  [7:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [C_M_AXI_GMEM2_ARUSER_WIDTH - 1:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [C_M_AXI_GMEM2_DATA_WIDTH - 1:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_RID;
input  [C_M_AXI_GMEM2_RUSER_WIDTH - 1:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [C_M_AXI_GMEM2_ID_WIDTH - 1:0] m_axi_gmem2_BID;
input  [C_M_AXI_GMEM2_BUSER_WIDTH - 1:0] m_axi_gmem2_BUSER;
input  [31:0] M;
input  [31:0] N_W1;
input  [31:0] N_W2;
input  [31:0] K;

 reg    ap_rst_n_inv;
wire   [15:0] temp_i_q0;
wire   [15:0] temp_i_q1;
wire   [15:0] temp_t_q0;
wire   [15:0] temp_t_q1;
wire   [15:0] temp_1_i_q0;
wire   [15:0] temp_1_i_q1;
wire   [15:0] temp_1_t_q0;
wire   [15:0] temp_1_t_q1;
wire   [15:0] temp_2_i_q0;
wire   [15:0] temp_2_i_q1;
wire   [15:0] temp_2_t_q0;
wire   [15:0] temp_2_t_q1;
wire   [15:0] temp_3_i_q0;
wire   [15:0] temp_3_i_q1;
wire   [15:0] temp_3_t_q0;
wire   [15:0] temp_3_t_q1;
wire   [15:0] temp_4_i_q0;
wire   [15:0] temp_4_i_q1;
wire   [15:0] temp_4_t_q0;
wire   [15:0] temp_4_t_q1;
wire   [15:0] temp_5_i_q0;
wire   [15:0] temp_5_i_q1;
wire   [15:0] temp_5_t_q0;
wire   [15:0] temp_5_t_q1;
wire   [15:0] temp_6_i_q0;
wire   [15:0] temp_6_i_q1;
wire   [15:0] temp_6_t_q0;
wire   [15:0] temp_6_t_q1;
wire   [15:0] temp_7_i_q0;
wire   [15:0] temp_7_i_q1;
wire   [15:0] temp_7_t_q0;
wire   [15:0] temp_7_t_q1;
wire   [15:0] temp_8_i_q0;
wire   [15:0] temp_8_i_q1;
wire   [15:0] temp_8_t_q0;
wire   [15:0] temp_8_t_q1;
wire   [15:0] temp_9_i_q0;
wire   [15:0] temp_9_i_q1;
wire   [15:0] temp_9_t_q0;
wire   [15:0] temp_9_t_q1;
wire   [15:0] temp_10_i_q0;
wire   [15:0] temp_10_i_q1;
wire   [15:0] temp_10_t_q0;
wire   [15:0] temp_10_t_q1;
wire   [15:0] temp_11_i_q0;
wire   [15:0] temp_11_i_q1;
wire   [15:0] temp_11_t_q0;
wire   [15:0] temp_11_t_q1;
wire   [15:0] temp_12_i_q0;
wire   [15:0] temp_12_i_q1;
wire   [15:0] temp_12_t_q0;
wire   [15:0] temp_12_t_q1;
wire   [15:0] temp_13_i_q0;
wire   [15:0] temp_13_i_q1;
wire   [15:0] temp_13_t_q0;
wire   [15:0] temp_13_t_q1;
wire   [15:0] temp_14_i_q0;
wire   [15:0] temp_14_i_q1;
wire   [15:0] temp_14_t_q0;
wire   [15:0] temp_14_t_q1;
wire   [15:0] temp_15_i_q0;
wire   [15:0] temp_15_i_q1;
wire   [15:0] temp_15_t_q0;
wire   [15:0] temp_15_t_q1;
wire   [63:0] A;
wire   [63:0] W1;
wire   [63:0] W2;
wire   [63:0] C;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    gmem0_0_AWREADY;
wire    gmem0_0_WREADY;
wire    gmem0_0_ARREADY;
wire    gmem0_0_RVALID;
wire   [15:0] gmem0_0_RDATA;
wire    gmem0_0_RLAST;
wire   [0:0] gmem0_0_RID;
wire   [9:0] gmem0_0_RFIFONUM;
wire   [0:0] gmem0_0_RUSER;
wire   [1:0] gmem0_0_RRESP;
wire    gmem0_0_BVALID;
wire   [1:0] gmem0_0_BRESP;
wire   [0:0] gmem0_0_BID;
wire   [0:0] gmem0_0_BUSER;
wire    gmem1_0_AWREADY;
wire    gmem1_0_WREADY;
wire    gmem1_0_ARREADY;
wire    gmem1_0_RVALID;
wire   [15:0] gmem1_0_RDATA;
wire    gmem1_0_RLAST;
wire   [0:0] gmem1_0_RID;
wire   [9:0] gmem1_0_RFIFONUM;
wire   [0:0] gmem1_0_RUSER;
wire   [1:0] gmem1_0_RRESP;
wire    gmem1_0_BVALID;
wire    gmem2_0_AWREADY;
wire    gmem2_0_WREADY;
wire    gmem2_0_ARREADY;
wire    gmem2_0_RVALID;
wire   [15:0] gmem2_0_RDATA;
wire    gmem2_0_RLAST;
wire   [0:0] gmem2_0_RID;
wire   [9:0] gmem2_0_RFIFONUM;
wire   [0:0] gmem2_0_RUSER;
wire   [1:0] gmem2_0_RRESP;
wire    gmem2_0_BVALID;
wire    qwen_linear_layer_U0_ap_start;
wire    qwen_linear_layer_U0_ap_done;
wire    qwen_linear_layer_U0_ap_continue;
wire    qwen_linear_layer_U0_ap_idle;
wire    qwen_linear_layer_U0_ap_ready;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_AWVALID;
wire   [63:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWADDR;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWID;
wire   [31:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWLEN;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWSIZE;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWBURST;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWLOCK;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWCACHE;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWPROT;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWQOS;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWREGION;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_AWUSER;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_WVALID;
wire   [15:0] qwen_linear_layer_U0_m_axi_gmem0_0_WDATA;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem0_0_WSTRB;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_WLAST;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_WID;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_WUSER;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_ARVALID;
wire   [63:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARADDR;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARID;
wire   [31:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARLEN;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARSIZE;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARBURST;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARLOCK;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARCACHE;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARPROT;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARQOS;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARREGION;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem0_0_ARUSER;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_RREADY;
wire    qwen_linear_layer_U0_m_axi_gmem0_0_BREADY;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_AWVALID;
wire   [63:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWADDR;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWID;
wire   [31:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWLEN;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWSIZE;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWBURST;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWLOCK;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWCACHE;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWPROT;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWQOS;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWREGION;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_AWUSER;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_WVALID;
wire   [15:0] qwen_linear_layer_U0_m_axi_gmem1_0_WDATA;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem1_0_WSTRB;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_WLAST;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_WID;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_WUSER;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_ARVALID;
wire   [63:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARADDR;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARID;
wire   [31:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARLEN;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARSIZE;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARBURST;
wire   [1:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARLOCK;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARCACHE;
wire   [2:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARPROT;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARQOS;
wire   [3:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARREGION;
wire   [0:0] qwen_linear_layer_U0_m_axi_gmem1_0_ARUSER;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_RREADY;
wire    qwen_linear_layer_U0_m_axi_gmem1_0_BREADY;
wire   [10:0] qwen_linear_layer_U0_C_0_address0;
wire    qwen_linear_layer_U0_C_0_ce0;
wire    qwen_linear_layer_U0_C_0_we0;
wire   [15:0] qwen_linear_layer_U0_C_0_d0;
wire   [10:0] qwen_linear_layer_U0_C_0_address1;
wire    qwen_linear_layer_U0_C_0_ce1;
wire    qwen_linear_layer_U0_C_0_we1;
wire   [15:0] qwen_linear_layer_U0_C_0_d1;
wire   [10:0] qwen_linear_layer_U0_C_1_address0;
wire    qwen_linear_layer_U0_C_1_ce0;
wire    qwen_linear_layer_U0_C_1_we0;
wire   [15:0] qwen_linear_layer_U0_C_1_d0;
wire   [10:0] qwen_linear_layer_U0_C_1_address1;
wire    qwen_linear_layer_U0_C_1_ce1;
wire    qwen_linear_layer_U0_C_1_we1;
wire   [15:0] qwen_linear_layer_U0_C_1_d1;
wire   [10:0] qwen_linear_layer_U0_C_2_address0;
wire    qwen_linear_layer_U0_C_2_ce0;
wire    qwen_linear_layer_U0_C_2_we0;
wire   [15:0] qwen_linear_layer_U0_C_2_d0;
wire   [10:0] qwen_linear_layer_U0_C_2_address1;
wire    qwen_linear_layer_U0_C_2_ce1;
wire    qwen_linear_layer_U0_C_2_we1;
wire   [15:0] qwen_linear_layer_U0_C_2_d1;
wire   [10:0] qwen_linear_layer_U0_C_3_address0;
wire    qwen_linear_layer_U0_C_3_ce0;
wire    qwen_linear_layer_U0_C_3_we0;
wire   [15:0] qwen_linear_layer_U0_C_3_d0;
wire   [10:0] qwen_linear_layer_U0_C_3_address1;
wire    qwen_linear_layer_U0_C_3_ce1;
wire    qwen_linear_layer_U0_C_3_we1;
wire   [15:0] qwen_linear_layer_U0_C_3_d1;
wire   [10:0] qwen_linear_layer_U0_C_4_address0;
wire    qwen_linear_layer_U0_C_4_ce0;
wire    qwen_linear_layer_U0_C_4_we0;
wire   [15:0] qwen_linear_layer_U0_C_4_d0;
wire   [10:0] qwen_linear_layer_U0_C_4_address1;
wire    qwen_linear_layer_U0_C_4_ce1;
wire    qwen_linear_layer_U0_C_4_we1;
wire   [15:0] qwen_linear_layer_U0_C_4_d1;
wire   [10:0] qwen_linear_layer_U0_C_5_address0;
wire    qwen_linear_layer_U0_C_5_ce0;
wire    qwen_linear_layer_U0_C_5_we0;
wire   [15:0] qwen_linear_layer_U0_C_5_d0;
wire   [10:0] qwen_linear_layer_U0_C_5_address1;
wire    qwen_linear_layer_U0_C_5_ce1;
wire    qwen_linear_layer_U0_C_5_we1;
wire   [15:0] qwen_linear_layer_U0_C_5_d1;
wire   [10:0] qwen_linear_layer_U0_C_6_address0;
wire    qwen_linear_layer_U0_C_6_ce0;
wire    qwen_linear_layer_U0_C_6_we0;
wire   [15:0] qwen_linear_layer_U0_C_6_d0;
wire   [10:0] qwen_linear_layer_U0_C_6_address1;
wire    qwen_linear_layer_U0_C_6_ce1;
wire    qwen_linear_layer_U0_C_6_we1;
wire   [15:0] qwen_linear_layer_U0_C_6_d1;
wire   [10:0] qwen_linear_layer_U0_C_7_address0;
wire    qwen_linear_layer_U0_C_7_ce0;
wire    qwen_linear_layer_U0_C_7_we0;
wire   [15:0] qwen_linear_layer_U0_C_7_d0;
wire   [10:0] qwen_linear_layer_U0_C_7_address1;
wire    qwen_linear_layer_U0_C_7_ce1;
wire    qwen_linear_layer_U0_C_7_we1;
wire   [15:0] qwen_linear_layer_U0_C_7_d1;
wire   [10:0] qwen_linear_layer_U0_C_8_address0;
wire    qwen_linear_layer_U0_C_8_ce0;
wire    qwen_linear_layer_U0_C_8_we0;
wire   [15:0] qwen_linear_layer_U0_C_8_d0;
wire   [10:0] qwen_linear_layer_U0_C_8_address1;
wire    qwen_linear_layer_U0_C_8_ce1;
wire    qwen_linear_layer_U0_C_8_we1;
wire   [15:0] qwen_linear_layer_U0_C_8_d1;
wire   [10:0] qwen_linear_layer_U0_C_9_address0;
wire    qwen_linear_layer_U0_C_9_ce0;
wire    qwen_linear_layer_U0_C_9_we0;
wire   [15:0] qwen_linear_layer_U0_C_9_d0;
wire   [10:0] qwen_linear_layer_U0_C_9_address1;
wire    qwen_linear_layer_U0_C_9_ce1;
wire    qwen_linear_layer_U0_C_9_we1;
wire   [15:0] qwen_linear_layer_U0_C_9_d1;
wire   [10:0] qwen_linear_layer_U0_C_10_address0;
wire    qwen_linear_layer_U0_C_10_ce0;
wire    qwen_linear_layer_U0_C_10_we0;
wire   [15:0] qwen_linear_layer_U0_C_10_d0;
wire   [10:0] qwen_linear_layer_U0_C_10_address1;
wire    qwen_linear_layer_U0_C_10_ce1;
wire    qwen_linear_layer_U0_C_10_we1;
wire   [15:0] qwen_linear_layer_U0_C_10_d1;
wire   [10:0] qwen_linear_layer_U0_C_11_address0;
wire    qwen_linear_layer_U0_C_11_ce0;
wire    qwen_linear_layer_U0_C_11_we0;
wire   [15:0] qwen_linear_layer_U0_C_11_d0;
wire   [10:0] qwen_linear_layer_U0_C_11_address1;
wire    qwen_linear_layer_U0_C_11_ce1;
wire    qwen_linear_layer_U0_C_11_we1;
wire   [15:0] qwen_linear_layer_U0_C_11_d1;
wire   [10:0] qwen_linear_layer_U0_C_12_address0;
wire    qwen_linear_layer_U0_C_12_ce0;
wire    qwen_linear_layer_U0_C_12_we0;
wire   [15:0] qwen_linear_layer_U0_C_12_d0;
wire   [10:0] qwen_linear_layer_U0_C_12_address1;
wire    qwen_linear_layer_U0_C_12_ce1;
wire    qwen_linear_layer_U0_C_12_we1;
wire   [15:0] qwen_linear_layer_U0_C_12_d1;
wire   [10:0] qwen_linear_layer_U0_C_13_address0;
wire    qwen_linear_layer_U0_C_13_ce0;
wire    qwen_linear_layer_U0_C_13_we0;
wire   [15:0] qwen_linear_layer_U0_C_13_d0;
wire   [10:0] qwen_linear_layer_U0_C_13_address1;
wire    qwen_linear_layer_U0_C_13_ce1;
wire    qwen_linear_layer_U0_C_13_we1;
wire   [15:0] qwen_linear_layer_U0_C_13_d1;
wire   [10:0] qwen_linear_layer_U0_C_14_address0;
wire    qwen_linear_layer_U0_C_14_ce0;
wire    qwen_linear_layer_U0_C_14_we0;
wire   [15:0] qwen_linear_layer_U0_C_14_d0;
wire   [10:0] qwen_linear_layer_U0_C_14_address1;
wire    qwen_linear_layer_U0_C_14_ce1;
wire    qwen_linear_layer_U0_C_14_we1;
wire   [15:0] qwen_linear_layer_U0_C_14_d1;
wire   [10:0] qwen_linear_layer_U0_C_15_address0;
wire    qwen_linear_layer_U0_C_15_ce0;
wire    qwen_linear_layer_U0_C_15_we0;
wire   [15:0] qwen_linear_layer_U0_C_15_d0;
wire   [10:0] qwen_linear_layer_U0_C_15_address1;
wire    qwen_linear_layer_U0_C_15_ce1;
wire    qwen_linear_layer_U0_C_15_we1;
wire   [15:0] qwen_linear_layer_U0_C_15_d1;
wire    ap_channel_done_temp_15;
wire    qwen_linear_layer_U0_C_15_full_n;
reg    ap_sync_reg_channel_write_temp_15;
wire    ap_sync_channel_write_temp_15;
wire    qwen_linear_layer_1_U0_ap_start;
wire    qwen_linear_layer_1_U0_ap_done;
wire    qwen_linear_layer_1_U0_ap_continue;
wire    qwen_linear_layer_1_U0_ap_idle;
wire    qwen_linear_layer_1_U0_ap_ready;
wire   [10:0] qwen_linear_layer_1_U0_A_0_address0;
wire    qwen_linear_layer_1_U0_A_0_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_0_address1;
wire    qwen_linear_layer_1_U0_A_0_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_1_address0;
wire    qwen_linear_layer_1_U0_A_1_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_1_address1;
wire    qwen_linear_layer_1_U0_A_1_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_2_address0;
wire    qwen_linear_layer_1_U0_A_2_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_2_address1;
wire    qwen_linear_layer_1_U0_A_2_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_3_address0;
wire    qwen_linear_layer_1_U0_A_3_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_3_address1;
wire    qwen_linear_layer_1_U0_A_3_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_4_address0;
wire    qwen_linear_layer_1_U0_A_4_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_4_address1;
wire    qwen_linear_layer_1_U0_A_4_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_5_address0;
wire    qwen_linear_layer_1_U0_A_5_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_5_address1;
wire    qwen_linear_layer_1_U0_A_5_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_6_address0;
wire    qwen_linear_layer_1_U0_A_6_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_6_address1;
wire    qwen_linear_layer_1_U0_A_6_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_7_address0;
wire    qwen_linear_layer_1_U0_A_7_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_7_address1;
wire    qwen_linear_layer_1_U0_A_7_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_8_address0;
wire    qwen_linear_layer_1_U0_A_8_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_8_address1;
wire    qwen_linear_layer_1_U0_A_8_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_9_address0;
wire    qwen_linear_layer_1_U0_A_9_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_9_address1;
wire    qwen_linear_layer_1_U0_A_9_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_10_address0;
wire    qwen_linear_layer_1_U0_A_10_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_10_address1;
wire    qwen_linear_layer_1_U0_A_10_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_11_address0;
wire    qwen_linear_layer_1_U0_A_11_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_11_address1;
wire    qwen_linear_layer_1_U0_A_11_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_12_address0;
wire    qwen_linear_layer_1_U0_A_12_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_12_address1;
wire    qwen_linear_layer_1_U0_A_12_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_13_address0;
wire    qwen_linear_layer_1_U0_A_13_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_13_address1;
wire    qwen_linear_layer_1_U0_A_13_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_14_address0;
wire    qwen_linear_layer_1_U0_A_14_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_14_address1;
wire    qwen_linear_layer_1_U0_A_14_ce1;
wire   [10:0] qwen_linear_layer_1_U0_A_15_address0;
wire    qwen_linear_layer_1_U0_A_15_ce0;
wire   [10:0] qwen_linear_layer_1_U0_A_15_address1;
wire    qwen_linear_layer_1_U0_A_15_ce1;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_AWVALID;
wire   [63:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWADDR;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWID;
wire   [31:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWLEN;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWSIZE;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWBURST;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWLOCK;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWCACHE;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWPROT;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWQOS;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWREGION;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_AWUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_WVALID;
wire   [15:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_WDATA;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_WSTRB;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_WLAST;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_WID;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_WUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_ARVALID;
wire   [63:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARADDR;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARID;
wire   [31:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARLEN;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARSIZE;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARBURST;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARLOCK;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARCACHE;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARPROT;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARQOS;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARREGION;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem2_0_ARUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_RREADY;
wire    qwen_linear_layer_1_U0_m_axi_gmem2_0_BREADY;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_AWVALID;
wire   [63:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWADDR;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWID;
wire   [31:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWLEN;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWSIZE;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWBURST;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWLOCK;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWCACHE;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWPROT;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWQOS;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWREGION;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_AWUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_WVALID;
wire   [15:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_WDATA;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_WSTRB;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_WLAST;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_WID;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_WUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_ARVALID;
wire   [63:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARADDR;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARID;
wire   [31:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARLEN;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARSIZE;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARBURST;
wire   [1:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARLOCK;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARCACHE;
wire   [2:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARPROT;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARQOS;
wire   [3:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARREGION;
wire   [0:0] qwen_linear_layer_1_U0_m_axi_gmem0_0_ARUSER;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_RREADY;
wire    qwen_linear_layer_1_U0_m_axi_gmem0_0_BREADY;
wire    temp_i_full_n;
wire    temp_t_empty_n;
wire    temp_1_i_full_n;
wire    temp_1_t_empty_n;
wire    temp_2_i_full_n;
wire    temp_2_t_empty_n;
wire    temp_3_i_full_n;
wire    temp_3_t_empty_n;
wire    temp_4_i_full_n;
wire    temp_4_t_empty_n;
wire    temp_5_i_full_n;
wire    temp_5_t_empty_n;
wire    temp_6_i_full_n;
wire    temp_6_t_empty_n;
wire    temp_7_i_full_n;
wire    temp_7_t_empty_n;
wire    temp_8_i_full_n;
wire    temp_8_t_empty_n;
wire    temp_9_i_full_n;
wire    temp_9_t_empty_n;
wire    temp_10_i_full_n;
wire    temp_10_t_empty_n;
wire    temp_11_i_full_n;
wire    temp_11_t_empty_n;
wire    temp_12_i_full_n;
wire    temp_12_t_empty_n;
wire    temp_13_i_full_n;
wire    temp_13_t_empty_n;
wire    temp_14_i_full_n;
wire    temp_14_t_empty_n;
wire    temp_15_i_full_n;
wire    temp_15_t_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_qwen_linear_layer_U0_ap_ready;
wire    ap_sync_qwen_linear_layer_U0_ap_ready;
reg    ap_sync_reg_qwen_linear_layer_1_U0_ap_ready;
wire    ap_sync_qwen_linear_layer_1_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_temp_15 = 1'b0;
#0 ap_sync_reg_qwen_linear_layer_U0_ap_ready = 1'b0;
#0 ap_sync_reg_qwen_linear_layer_1_U0_ap_ready = 1'b0;
end

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_0_address0),
    .i_ce0(qwen_linear_layer_U0_C_0_ce0),
    .i_we0(qwen_linear_layer_U0_C_0_we0),
    .i_d0(qwen_linear_layer_U0_C_0_d0),
    .i_q0(temp_i_q0),
    .i_address1(qwen_linear_layer_U0_C_0_address1),
    .i_ce1(qwen_linear_layer_U0_C_0_ce1),
    .i_we1(qwen_linear_layer_U0_C_0_we1),
    .i_d1(qwen_linear_layer_U0_C_0_d1),
    .i_q1(temp_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_0_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_0_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_0_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_1_address0),
    .i_ce0(qwen_linear_layer_U0_C_1_ce0),
    .i_we0(qwen_linear_layer_U0_C_1_we0),
    .i_d0(qwen_linear_layer_U0_C_1_d0),
    .i_q0(temp_1_i_q0),
    .i_address1(qwen_linear_layer_U0_C_1_address1),
    .i_ce1(qwen_linear_layer_U0_C_1_ce1),
    .i_we1(qwen_linear_layer_U0_C_1_we1),
    .i_d1(qwen_linear_layer_U0_C_1_d1),
    .i_q1(temp_1_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_1_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_1_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_1_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_1_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_1_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_1_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_1_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_2_address0),
    .i_ce0(qwen_linear_layer_U0_C_2_ce0),
    .i_we0(qwen_linear_layer_U0_C_2_we0),
    .i_d0(qwen_linear_layer_U0_C_2_d0),
    .i_q0(temp_2_i_q0),
    .i_address1(qwen_linear_layer_U0_C_2_address1),
    .i_ce1(qwen_linear_layer_U0_C_2_ce1),
    .i_we1(qwen_linear_layer_U0_C_2_we1),
    .i_d1(qwen_linear_layer_U0_C_2_d1),
    .i_q1(temp_2_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_2_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_2_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_2_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_2_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_2_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_2_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_2_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_2_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_3_address0),
    .i_ce0(qwen_linear_layer_U0_C_3_ce0),
    .i_we0(qwen_linear_layer_U0_C_3_we0),
    .i_d0(qwen_linear_layer_U0_C_3_d0),
    .i_q0(temp_3_i_q0),
    .i_address1(qwen_linear_layer_U0_C_3_address1),
    .i_ce1(qwen_linear_layer_U0_C_3_ce1),
    .i_we1(qwen_linear_layer_U0_C_3_we1),
    .i_d1(qwen_linear_layer_U0_C_3_d1),
    .i_q1(temp_3_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_3_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_3_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_3_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_3_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_3_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_3_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_3_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_3_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_4_address0),
    .i_ce0(qwen_linear_layer_U0_C_4_ce0),
    .i_we0(qwen_linear_layer_U0_C_4_we0),
    .i_d0(qwen_linear_layer_U0_C_4_d0),
    .i_q0(temp_4_i_q0),
    .i_address1(qwen_linear_layer_U0_C_4_address1),
    .i_ce1(qwen_linear_layer_U0_C_4_ce1),
    .i_we1(qwen_linear_layer_U0_C_4_we1),
    .i_d1(qwen_linear_layer_U0_C_4_d1),
    .i_q1(temp_4_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_4_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_4_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_4_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_4_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_4_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_4_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_4_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_4_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_5_address0),
    .i_ce0(qwen_linear_layer_U0_C_5_ce0),
    .i_we0(qwen_linear_layer_U0_C_5_we0),
    .i_d0(qwen_linear_layer_U0_C_5_d0),
    .i_q0(temp_5_i_q0),
    .i_address1(qwen_linear_layer_U0_C_5_address1),
    .i_ce1(qwen_linear_layer_U0_C_5_ce1),
    .i_we1(qwen_linear_layer_U0_C_5_we1),
    .i_d1(qwen_linear_layer_U0_C_5_d1),
    .i_q1(temp_5_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_5_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_5_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_5_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_5_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_5_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_5_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_5_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_5_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_6_address0),
    .i_ce0(qwen_linear_layer_U0_C_6_ce0),
    .i_we0(qwen_linear_layer_U0_C_6_we0),
    .i_d0(qwen_linear_layer_U0_C_6_d0),
    .i_q0(temp_6_i_q0),
    .i_address1(qwen_linear_layer_U0_C_6_address1),
    .i_ce1(qwen_linear_layer_U0_C_6_ce1),
    .i_we1(qwen_linear_layer_U0_C_6_we1),
    .i_d1(qwen_linear_layer_U0_C_6_d1),
    .i_q1(temp_6_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_6_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_6_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_6_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_6_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_6_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_6_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_6_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_6_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_7_address0),
    .i_ce0(qwen_linear_layer_U0_C_7_ce0),
    .i_we0(qwen_linear_layer_U0_C_7_we0),
    .i_d0(qwen_linear_layer_U0_C_7_d0),
    .i_q0(temp_7_i_q0),
    .i_address1(qwen_linear_layer_U0_C_7_address1),
    .i_ce1(qwen_linear_layer_U0_C_7_ce1),
    .i_we1(qwen_linear_layer_U0_C_7_we1),
    .i_d1(qwen_linear_layer_U0_C_7_d1),
    .i_q1(temp_7_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_7_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_7_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_7_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_7_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_7_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_7_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_7_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_7_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_8_address0),
    .i_ce0(qwen_linear_layer_U0_C_8_ce0),
    .i_we0(qwen_linear_layer_U0_C_8_we0),
    .i_d0(qwen_linear_layer_U0_C_8_d0),
    .i_q0(temp_8_i_q0),
    .i_address1(qwen_linear_layer_U0_C_8_address1),
    .i_ce1(qwen_linear_layer_U0_C_8_ce1),
    .i_we1(qwen_linear_layer_U0_C_8_we1),
    .i_d1(qwen_linear_layer_U0_C_8_d1),
    .i_q1(temp_8_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_8_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_8_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_8_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_8_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_8_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_8_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_8_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_8_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_9_address0),
    .i_ce0(qwen_linear_layer_U0_C_9_ce0),
    .i_we0(qwen_linear_layer_U0_C_9_we0),
    .i_d0(qwen_linear_layer_U0_C_9_d0),
    .i_q0(temp_9_i_q0),
    .i_address1(qwen_linear_layer_U0_C_9_address1),
    .i_ce1(qwen_linear_layer_U0_C_9_ce1),
    .i_we1(qwen_linear_layer_U0_C_9_we1),
    .i_d1(qwen_linear_layer_U0_C_9_d1),
    .i_q1(temp_9_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_9_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_9_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_9_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_9_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_9_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_9_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_9_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_9_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_10_address0),
    .i_ce0(qwen_linear_layer_U0_C_10_ce0),
    .i_we0(qwen_linear_layer_U0_C_10_we0),
    .i_d0(qwen_linear_layer_U0_C_10_d0),
    .i_q0(temp_10_i_q0),
    .i_address1(qwen_linear_layer_U0_C_10_address1),
    .i_ce1(qwen_linear_layer_U0_C_10_ce1),
    .i_we1(qwen_linear_layer_U0_C_10_we1),
    .i_d1(qwen_linear_layer_U0_C_10_d1),
    .i_q1(temp_10_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_10_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_10_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_10_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_10_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_10_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_10_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_10_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_10_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_11_address0),
    .i_ce0(qwen_linear_layer_U0_C_11_ce0),
    .i_we0(qwen_linear_layer_U0_C_11_we0),
    .i_d0(qwen_linear_layer_U0_C_11_d0),
    .i_q0(temp_11_i_q0),
    .i_address1(qwen_linear_layer_U0_C_11_address1),
    .i_ce1(qwen_linear_layer_U0_C_11_ce1),
    .i_we1(qwen_linear_layer_U0_C_11_we1),
    .i_d1(qwen_linear_layer_U0_C_11_d1),
    .i_q1(temp_11_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_11_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_11_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_11_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_11_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_11_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_11_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_11_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_11_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_12_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_12_address0),
    .i_ce0(qwen_linear_layer_U0_C_12_ce0),
    .i_we0(qwen_linear_layer_U0_C_12_we0),
    .i_d0(qwen_linear_layer_U0_C_12_d0),
    .i_q0(temp_12_i_q0),
    .i_address1(qwen_linear_layer_U0_C_12_address1),
    .i_ce1(qwen_linear_layer_U0_C_12_ce1),
    .i_we1(qwen_linear_layer_U0_C_12_we1),
    .i_d1(qwen_linear_layer_U0_C_12_d1),
    .i_q1(temp_12_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_12_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_12_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_12_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_12_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_12_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_12_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_12_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_12_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_13_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_13_address0),
    .i_ce0(qwen_linear_layer_U0_C_13_ce0),
    .i_we0(qwen_linear_layer_U0_C_13_we0),
    .i_d0(qwen_linear_layer_U0_C_13_d0),
    .i_q0(temp_13_i_q0),
    .i_address1(qwen_linear_layer_U0_C_13_address1),
    .i_ce1(qwen_linear_layer_U0_C_13_ce1),
    .i_we1(qwen_linear_layer_U0_C_13_we1),
    .i_d1(qwen_linear_layer_U0_C_13_d1),
    .i_q1(temp_13_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_13_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_13_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_13_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_13_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_13_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_13_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_13_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_13_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_14_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_14_address0),
    .i_ce0(qwen_linear_layer_U0_C_14_ce0),
    .i_we0(qwen_linear_layer_U0_C_14_we0),
    .i_d0(qwen_linear_layer_U0_C_14_d0),
    .i_q0(temp_14_i_q0),
    .i_address1(qwen_linear_layer_U0_C_14_address1),
    .i_ce1(qwen_linear_layer_U0_C_14_ce1),
    .i_we1(qwen_linear_layer_U0_C_14_we1),
    .i_d1(qwen_linear_layer_U0_C_14_d1),
    .i_q1(temp_14_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_14_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_14_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_14_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_14_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_14_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_14_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_14_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_14_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_temp_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 1792 ),
    .AddressWidth( 11 ))
temp_15_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(qwen_linear_layer_U0_C_15_address0),
    .i_ce0(qwen_linear_layer_U0_C_15_ce0),
    .i_we0(qwen_linear_layer_U0_C_15_we0),
    .i_d0(qwen_linear_layer_U0_C_15_d0),
    .i_q0(temp_15_i_q0),
    .i_address1(qwen_linear_layer_U0_C_15_address1),
    .i_ce1(qwen_linear_layer_U0_C_15_ce1),
    .i_we1(qwen_linear_layer_U0_C_15_we1),
    .i_d1(qwen_linear_layer_U0_C_15_d1),
    .i_q1(temp_15_i_q1),
    .t_address0(qwen_linear_layer_1_U0_A_15_address0),
    .t_ce0(qwen_linear_layer_1_U0_A_15_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(temp_15_t_q0),
    .t_address1(qwen_linear_layer_1_U0_A_15_address1),
    .t_ce1(qwen_linear_layer_1_U0_A_15_ce1),
    .t_we1(1'b0),
    .t_d1(16'd0),
    .t_q1(temp_15_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(temp_15_i_full_n),
    .i_write(ap_channel_done_temp_15),
    .t_empty_n(temp_15_t_empty_n),
    .t_read(qwen_linear_layer_1_U0_ap_ready)
);

qwen_superblock_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A(A),
    .W1(W1),
    .W2(W2),
    .C(C),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

qwen_superblock_gmem0_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM0_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM0_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM0_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM0_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM0_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM0_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM0_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM0_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM0_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM0_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM0_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem0_m_axi_U(
    .AWVALID(m_axi_gmem0_AWVALID),
    .AWREADY(m_axi_gmem0_AWREADY),
    .AWADDR(m_axi_gmem0_AWADDR),
    .AWID(m_axi_gmem0_AWID),
    .AWLEN(m_axi_gmem0_AWLEN),
    .AWSIZE(m_axi_gmem0_AWSIZE),
    .AWBURST(m_axi_gmem0_AWBURST),
    .AWLOCK(m_axi_gmem0_AWLOCK),
    .AWCACHE(m_axi_gmem0_AWCACHE),
    .AWPROT(m_axi_gmem0_AWPROT),
    .AWQOS(m_axi_gmem0_AWQOS),
    .AWREGION(m_axi_gmem0_AWREGION),
    .AWUSER(m_axi_gmem0_AWUSER),
    .WVALID(m_axi_gmem0_WVALID),
    .WREADY(m_axi_gmem0_WREADY),
    .WDATA(m_axi_gmem0_WDATA),
    .WSTRB(m_axi_gmem0_WSTRB),
    .WLAST(m_axi_gmem0_WLAST),
    .WID(m_axi_gmem0_WID),
    .WUSER(m_axi_gmem0_WUSER),
    .ARVALID(m_axi_gmem0_ARVALID),
    .ARREADY(m_axi_gmem0_ARREADY),
    .ARADDR(m_axi_gmem0_ARADDR),
    .ARID(m_axi_gmem0_ARID),
    .ARLEN(m_axi_gmem0_ARLEN),
    .ARSIZE(m_axi_gmem0_ARSIZE),
    .ARBURST(m_axi_gmem0_ARBURST),
    .ARLOCK(m_axi_gmem0_ARLOCK),
    .ARCACHE(m_axi_gmem0_ARCACHE),
    .ARPROT(m_axi_gmem0_ARPROT),
    .ARQOS(m_axi_gmem0_ARQOS),
    .ARREGION(m_axi_gmem0_ARREGION),
    .ARUSER(m_axi_gmem0_ARUSER),
    .RVALID(m_axi_gmem0_RVALID),
    .RREADY(m_axi_gmem0_RREADY),
    .RDATA(m_axi_gmem0_RDATA),
    .RLAST(m_axi_gmem0_RLAST),
    .RID(m_axi_gmem0_RID),
    .RUSER(m_axi_gmem0_RUSER),
    .RRESP(m_axi_gmem0_RRESP),
    .BVALID(m_axi_gmem0_BVALID),
    .BREADY(m_axi_gmem0_BREADY),
    .BRESP(m_axi_gmem0_BRESP),
    .BID(m_axi_gmem0_BID),
    .BUSER(m_axi_gmem0_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(qwen_linear_layer_U0_m_axi_gmem0_0_ARVALID),
    .I_CH0_ARREADY(gmem0_0_ARREADY),
    .I_CH0_ARADDR(qwen_linear_layer_U0_m_axi_gmem0_0_ARADDR),
    .I_CH0_ARLEN(qwen_linear_layer_U0_m_axi_gmem0_0_ARLEN),
    .I_CH0_RVALID(gmem0_0_RVALID),
    .I_CH0_RREADY(qwen_linear_layer_U0_m_axi_gmem0_0_RREADY),
    .I_CH0_RDATA(gmem0_0_RDATA),
    .I_CH0_RFIFONUM(gmem0_0_RFIFONUM),
    .I_CH0_AWVALID(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWVALID),
    .I_CH0_AWREADY(gmem0_0_AWREADY),
    .I_CH0_AWADDR(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWADDR),
    .I_CH0_AWLEN(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWLEN),
    .I_CH0_WVALID(qwen_linear_layer_1_U0_m_axi_gmem0_0_WVALID),
    .I_CH0_WREADY(gmem0_0_WREADY),
    .I_CH0_WDATA(qwen_linear_layer_1_U0_m_axi_gmem0_0_WDATA),
    .I_CH0_WSTRB(qwen_linear_layer_1_U0_m_axi_gmem0_0_WSTRB),
    .I_CH0_BVALID(gmem0_0_BVALID),
    .I_CH0_BREADY(qwen_linear_layer_1_U0_m_axi_gmem0_0_BREADY)
);

qwen_superblock_gmem1_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM1_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem1_m_axi_U(
    .AWVALID(m_axi_gmem1_AWVALID),
    .AWREADY(m_axi_gmem1_AWREADY),
    .AWADDR(m_axi_gmem1_AWADDR),
    .AWID(m_axi_gmem1_AWID),
    .AWLEN(m_axi_gmem1_AWLEN),
    .AWSIZE(m_axi_gmem1_AWSIZE),
    .AWBURST(m_axi_gmem1_AWBURST),
    .AWLOCK(m_axi_gmem1_AWLOCK),
    .AWCACHE(m_axi_gmem1_AWCACHE),
    .AWPROT(m_axi_gmem1_AWPROT),
    .AWQOS(m_axi_gmem1_AWQOS),
    .AWREGION(m_axi_gmem1_AWREGION),
    .AWUSER(m_axi_gmem1_AWUSER),
    .WVALID(m_axi_gmem1_WVALID),
    .WREADY(m_axi_gmem1_WREADY),
    .WDATA(m_axi_gmem1_WDATA),
    .WSTRB(m_axi_gmem1_WSTRB),
    .WLAST(m_axi_gmem1_WLAST),
    .WID(m_axi_gmem1_WID),
    .WUSER(m_axi_gmem1_WUSER),
    .ARVALID(m_axi_gmem1_ARVALID),
    .ARREADY(m_axi_gmem1_ARREADY),
    .ARADDR(m_axi_gmem1_ARADDR),
    .ARID(m_axi_gmem1_ARID),
    .ARLEN(m_axi_gmem1_ARLEN),
    .ARSIZE(m_axi_gmem1_ARSIZE),
    .ARBURST(m_axi_gmem1_ARBURST),
    .ARLOCK(m_axi_gmem1_ARLOCK),
    .ARCACHE(m_axi_gmem1_ARCACHE),
    .ARPROT(m_axi_gmem1_ARPROT),
    .ARQOS(m_axi_gmem1_ARQOS),
    .ARREGION(m_axi_gmem1_ARREGION),
    .ARUSER(m_axi_gmem1_ARUSER),
    .RVALID(m_axi_gmem1_RVALID),
    .RREADY(m_axi_gmem1_RREADY),
    .RDATA(m_axi_gmem1_RDATA),
    .RLAST(m_axi_gmem1_RLAST),
    .RID(m_axi_gmem1_RID),
    .RUSER(m_axi_gmem1_RUSER),
    .RRESP(m_axi_gmem1_RRESP),
    .BVALID(m_axi_gmem1_BVALID),
    .BREADY(m_axi_gmem1_BREADY),
    .BRESP(m_axi_gmem1_BRESP),
    .BID(m_axi_gmem1_BID),
    .BUSER(m_axi_gmem1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(qwen_linear_layer_U0_m_axi_gmem1_0_ARVALID),
    .I_CH0_ARREADY(gmem1_0_ARREADY),
    .I_CH0_ARADDR(qwen_linear_layer_U0_m_axi_gmem1_0_ARADDR),
    .I_CH0_ARLEN(qwen_linear_layer_U0_m_axi_gmem1_0_ARLEN),
    .I_CH0_RVALID(gmem1_0_RVALID),
    .I_CH0_RREADY(qwen_linear_layer_U0_m_axi_gmem1_0_RREADY),
    .I_CH0_RDATA(gmem1_0_RDATA),
    .I_CH0_RFIFONUM(gmem1_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem1_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem1_0_WREADY),
    .I_CH0_WDATA(16'd0),
    .I_CH0_WSTRB(2'd0),
    .I_CH0_BVALID(gmem1_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

qwen_superblock_gmem2_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM2_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 10 ),
    .CH0_USER_DW( 16 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
gmem2_m_axi_U(
    .AWVALID(m_axi_gmem2_AWVALID),
    .AWREADY(m_axi_gmem2_AWREADY),
    .AWADDR(m_axi_gmem2_AWADDR),
    .AWID(m_axi_gmem2_AWID),
    .AWLEN(m_axi_gmem2_AWLEN),
    .AWSIZE(m_axi_gmem2_AWSIZE),
    .AWBURST(m_axi_gmem2_AWBURST),
    .AWLOCK(m_axi_gmem2_AWLOCK),
    .AWCACHE(m_axi_gmem2_AWCACHE),
    .AWPROT(m_axi_gmem2_AWPROT),
    .AWQOS(m_axi_gmem2_AWQOS),
    .AWREGION(m_axi_gmem2_AWREGION),
    .AWUSER(m_axi_gmem2_AWUSER),
    .WVALID(m_axi_gmem2_WVALID),
    .WREADY(m_axi_gmem2_WREADY),
    .WDATA(m_axi_gmem2_WDATA),
    .WSTRB(m_axi_gmem2_WSTRB),
    .WLAST(m_axi_gmem2_WLAST),
    .WID(m_axi_gmem2_WID),
    .WUSER(m_axi_gmem2_WUSER),
    .ARVALID(m_axi_gmem2_ARVALID),
    .ARREADY(m_axi_gmem2_ARREADY),
    .ARADDR(m_axi_gmem2_ARADDR),
    .ARID(m_axi_gmem2_ARID),
    .ARLEN(m_axi_gmem2_ARLEN),
    .ARSIZE(m_axi_gmem2_ARSIZE),
    .ARBURST(m_axi_gmem2_ARBURST),
    .ARLOCK(m_axi_gmem2_ARLOCK),
    .ARCACHE(m_axi_gmem2_ARCACHE),
    .ARPROT(m_axi_gmem2_ARPROT),
    .ARQOS(m_axi_gmem2_ARQOS),
    .ARREGION(m_axi_gmem2_ARREGION),
    .ARUSER(m_axi_gmem2_ARUSER),
    .RVALID(m_axi_gmem2_RVALID),
    .RREADY(m_axi_gmem2_RREADY),
    .RDATA(m_axi_gmem2_RDATA),
    .RLAST(m_axi_gmem2_RLAST),
    .RID(m_axi_gmem2_RID),
    .RUSER(m_axi_gmem2_RUSER),
    .RRESP(m_axi_gmem2_RRESP),
    .BVALID(m_axi_gmem2_BVALID),
    .BREADY(m_axi_gmem2_BREADY),
    .BRESP(m_axi_gmem2_BRESP),
    .BID(m_axi_gmem2_BID),
    .BUSER(m_axi_gmem2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARVALID),
    .I_CH0_ARREADY(gmem2_0_ARREADY),
    .I_CH0_ARADDR(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARADDR),
    .I_CH0_ARLEN(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARLEN),
    .I_CH0_RVALID(gmem2_0_RVALID),
    .I_CH0_RREADY(qwen_linear_layer_1_U0_m_axi_gmem2_0_RREADY),
    .I_CH0_RDATA(gmem2_0_RDATA),
    .I_CH0_RFIFONUM(gmem2_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(gmem2_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(gmem2_0_WREADY),
    .I_CH0_WDATA(16'd0),
    .I_CH0_WSTRB(2'd0),
    .I_CH0_BVALID(gmem2_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

qwen_superblock_qwen_linear_layer qwen_linear_layer_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(qwen_linear_layer_U0_ap_start),
    .ap_done(qwen_linear_layer_U0_ap_done),
    .ap_continue(qwen_linear_layer_U0_ap_continue),
    .ap_idle(qwen_linear_layer_U0_ap_idle),
    .ap_ready(qwen_linear_layer_U0_ap_ready),
    .m_axi_gmem0_0_AWVALID(qwen_linear_layer_U0_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(1'b0),
    .m_axi_gmem0_0_AWADDR(qwen_linear_layer_U0_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(qwen_linear_layer_U0_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(qwen_linear_layer_U0_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(qwen_linear_layer_U0_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(qwen_linear_layer_U0_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(qwen_linear_layer_U0_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(qwen_linear_layer_U0_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(qwen_linear_layer_U0_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(qwen_linear_layer_U0_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(qwen_linear_layer_U0_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(qwen_linear_layer_U0_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(qwen_linear_layer_U0_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(1'b0),
    .m_axi_gmem0_0_WDATA(qwen_linear_layer_U0_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(qwen_linear_layer_U0_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(qwen_linear_layer_U0_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(qwen_linear_layer_U0_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(qwen_linear_layer_U0_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(qwen_linear_layer_U0_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(gmem0_0_ARREADY),
    .m_axi_gmem0_0_ARADDR(qwen_linear_layer_U0_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(qwen_linear_layer_U0_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(qwen_linear_layer_U0_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(qwen_linear_layer_U0_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(qwen_linear_layer_U0_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(qwen_linear_layer_U0_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(qwen_linear_layer_U0_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(qwen_linear_layer_U0_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(qwen_linear_layer_U0_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(qwen_linear_layer_U0_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(qwen_linear_layer_U0_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(gmem0_0_RVALID),
    .m_axi_gmem0_0_RREADY(qwen_linear_layer_U0_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(gmem0_0_RDATA),
    .m_axi_gmem0_0_RLAST(gmem0_0_RLAST),
    .m_axi_gmem0_0_RID(gmem0_0_RID),
    .m_axi_gmem0_0_RFIFONUM(gmem0_0_RFIFONUM),
    .m_axi_gmem0_0_RUSER(gmem0_0_RUSER),
    .m_axi_gmem0_0_RRESP(gmem0_0_RRESP),
    .m_axi_gmem0_0_BVALID(1'b0),
    .m_axi_gmem0_0_BREADY(qwen_linear_layer_U0_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(2'd0),
    .m_axi_gmem0_0_BID(1'd0),
    .m_axi_gmem0_0_BUSER(1'd0),
    .A(A),
    .m_axi_gmem1_0_AWVALID(qwen_linear_layer_U0_m_axi_gmem1_0_AWVALID),
    .m_axi_gmem1_0_AWREADY(1'b0),
    .m_axi_gmem1_0_AWADDR(qwen_linear_layer_U0_m_axi_gmem1_0_AWADDR),
    .m_axi_gmem1_0_AWID(qwen_linear_layer_U0_m_axi_gmem1_0_AWID),
    .m_axi_gmem1_0_AWLEN(qwen_linear_layer_U0_m_axi_gmem1_0_AWLEN),
    .m_axi_gmem1_0_AWSIZE(qwen_linear_layer_U0_m_axi_gmem1_0_AWSIZE),
    .m_axi_gmem1_0_AWBURST(qwen_linear_layer_U0_m_axi_gmem1_0_AWBURST),
    .m_axi_gmem1_0_AWLOCK(qwen_linear_layer_U0_m_axi_gmem1_0_AWLOCK),
    .m_axi_gmem1_0_AWCACHE(qwen_linear_layer_U0_m_axi_gmem1_0_AWCACHE),
    .m_axi_gmem1_0_AWPROT(qwen_linear_layer_U0_m_axi_gmem1_0_AWPROT),
    .m_axi_gmem1_0_AWQOS(qwen_linear_layer_U0_m_axi_gmem1_0_AWQOS),
    .m_axi_gmem1_0_AWREGION(qwen_linear_layer_U0_m_axi_gmem1_0_AWREGION),
    .m_axi_gmem1_0_AWUSER(qwen_linear_layer_U0_m_axi_gmem1_0_AWUSER),
    .m_axi_gmem1_0_WVALID(qwen_linear_layer_U0_m_axi_gmem1_0_WVALID),
    .m_axi_gmem1_0_WREADY(1'b0),
    .m_axi_gmem1_0_WDATA(qwen_linear_layer_U0_m_axi_gmem1_0_WDATA),
    .m_axi_gmem1_0_WSTRB(qwen_linear_layer_U0_m_axi_gmem1_0_WSTRB),
    .m_axi_gmem1_0_WLAST(qwen_linear_layer_U0_m_axi_gmem1_0_WLAST),
    .m_axi_gmem1_0_WID(qwen_linear_layer_U0_m_axi_gmem1_0_WID),
    .m_axi_gmem1_0_WUSER(qwen_linear_layer_U0_m_axi_gmem1_0_WUSER),
    .m_axi_gmem1_0_ARVALID(qwen_linear_layer_U0_m_axi_gmem1_0_ARVALID),
    .m_axi_gmem1_0_ARREADY(gmem1_0_ARREADY),
    .m_axi_gmem1_0_ARADDR(qwen_linear_layer_U0_m_axi_gmem1_0_ARADDR),
    .m_axi_gmem1_0_ARID(qwen_linear_layer_U0_m_axi_gmem1_0_ARID),
    .m_axi_gmem1_0_ARLEN(qwen_linear_layer_U0_m_axi_gmem1_0_ARLEN),
    .m_axi_gmem1_0_ARSIZE(qwen_linear_layer_U0_m_axi_gmem1_0_ARSIZE),
    .m_axi_gmem1_0_ARBURST(qwen_linear_layer_U0_m_axi_gmem1_0_ARBURST),
    .m_axi_gmem1_0_ARLOCK(qwen_linear_layer_U0_m_axi_gmem1_0_ARLOCK),
    .m_axi_gmem1_0_ARCACHE(qwen_linear_layer_U0_m_axi_gmem1_0_ARCACHE),
    .m_axi_gmem1_0_ARPROT(qwen_linear_layer_U0_m_axi_gmem1_0_ARPROT),
    .m_axi_gmem1_0_ARQOS(qwen_linear_layer_U0_m_axi_gmem1_0_ARQOS),
    .m_axi_gmem1_0_ARREGION(qwen_linear_layer_U0_m_axi_gmem1_0_ARREGION),
    .m_axi_gmem1_0_ARUSER(qwen_linear_layer_U0_m_axi_gmem1_0_ARUSER),
    .m_axi_gmem1_0_RVALID(gmem1_0_RVALID),
    .m_axi_gmem1_0_RREADY(qwen_linear_layer_U0_m_axi_gmem1_0_RREADY),
    .m_axi_gmem1_0_RDATA(gmem1_0_RDATA),
    .m_axi_gmem1_0_RLAST(gmem1_0_RLAST),
    .m_axi_gmem1_0_RID(gmem1_0_RID),
    .m_axi_gmem1_0_RFIFONUM(gmem1_0_RFIFONUM),
    .m_axi_gmem1_0_RUSER(gmem1_0_RUSER),
    .m_axi_gmem1_0_RRESP(gmem1_0_RRESP),
    .m_axi_gmem1_0_BVALID(1'b0),
    .m_axi_gmem1_0_BREADY(qwen_linear_layer_U0_m_axi_gmem1_0_BREADY),
    .m_axi_gmem1_0_BRESP(2'd0),
    .m_axi_gmem1_0_BID(1'd0),
    .m_axi_gmem1_0_BUSER(1'd0),
    .W(W1),
    .C_0_address0(qwen_linear_layer_U0_C_0_address0),
    .C_0_ce0(qwen_linear_layer_U0_C_0_ce0),
    .C_0_we0(qwen_linear_layer_U0_C_0_we0),
    .C_0_d0(qwen_linear_layer_U0_C_0_d0),
    .C_0_address1(qwen_linear_layer_U0_C_0_address1),
    .C_0_ce1(qwen_linear_layer_U0_C_0_ce1),
    .C_0_we1(qwen_linear_layer_U0_C_0_we1),
    .C_0_d1(qwen_linear_layer_U0_C_0_d1),
    .C_1_address0(qwen_linear_layer_U0_C_1_address0),
    .C_1_ce0(qwen_linear_layer_U0_C_1_ce0),
    .C_1_we0(qwen_linear_layer_U0_C_1_we0),
    .C_1_d0(qwen_linear_layer_U0_C_1_d0),
    .C_1_address1(qwen_linear_layer_U0_C_1_address1),
    .C_1_ce1(qwen_linear_layer_U0_C_1_ce1),
    .C_1_we1(qwen_linear_layer_U0_C_1_we1),
    .C_1_d1(qwen_linear_layer_U0_C_1_d1),
    .C_2_address0(qwen_linear_layer_U0_C_2_address0),
    .C_2_ce0(qwen_linear_layer_U0_C_2_ce0),
    .C_2_we0(qwen_linear_layer_U0_C_2_we0),
    .C_2_d0(qwen_linear_layer_U0_C_2_d0),
    .C_2_address1(qwen_linear_layer_U0_C_2_address1),
    .C_2_ce1(qwen_linear_layer_U0_C_2_ce1),
    .C_2_we1(qwen_linear_layer_U0_C_2_we1),
    .C_2_d1(qwen_linear_layer_U0_C_2_d1),
    .C_3_address0(qwen_linear_layer_U0_C_3_address0),
    .C_3_ce0(qwen_linear_layer_U0_C_3_ce0),
    .C_3_we0(qwen_linear_layer_U0_C_3_we0),
    .C_3_d0(qwen_linear_layer_U0_C_3_d0),
    .C_3_address1(qwen_linear_layer_U0_C_3_address1),
    .C_3_ce1(qwen_linear_layer_U0_C_3_ce1),
    .C_3_we1(qwen_linear_layer_U0_C_3_we1),
    .C_3_d1(qwen_linear_layer_U0_C_3_d1),
    .C_4_address0(qwen_linear_layer_U0_C_4_address0),
    .C_4_ce0(qwen_linear_layer_U0_C_4_ce0),
    .C_4_we0(qwen_linear_layer_U0_C_4_we0),
    .C_4_d0(qwen_linear_layer_U0_C_4_d0),
    .C_4_address1(qwen_linear_layer_U0_C_4_address1),
    .C_4_ce1(qwen_linear_layer_U0_C_4_ce1),
    .C_4_we1(qwen_linear_layer_U0_C_4_we1),
    .C_4_d1(qwen_linear_layer_U0_C_4_d1),
    .C_5_address0(qwen_linear_layer_U0_C_5_address0),
    .C_5_ce0(qwen_linear_layer_U0_C_5_ce0),
    .C_5_we0(qwen_linear_layer_U0_C_5_we0),
    .C_5_d0(qwen_linear_layer_U0_C_5_d0),
    .C_5_address1(qwen_linear_layer_U0_C_5_address1),
    .C_5_ce1(qwen_linear_layer_U0_C_5_ce1),
    .C_5_we1(qwen_linear_layer_U0_C_5_we1),
    .C_5_d1(qwen_linear_layer_U0_C_5_d1),
    .C_6_address0(qwen_linear_layer_U0_C_6_address0),
    .C_6_ce0(qwen_linear_layer_U0_C_6_ce0),
    .C_6_we0(qwen_linear_layer_U0_C_6_we0),
    .C_6_d0(qwen_linear_layer_U0_C_6_d0),
    .C_6_address1(qwen_linear_layer_U0_C_6_address1),
    .C_6_ce1(qwen_linear_layer_U0_C_6_ce1),
    .C_6_we1(qwen_linear_layer_U0_C_6_we1),
    .C_6_d1(qwen_linear_layer_U0_C_6_d1),
    .C_7_address0(qwen_linear_layer_U0_C_7_address0),
    .C_7_ce0(qwen_linear_layer_U0_C_7_ce0),
    .C_7_we0(qwen_linear_layer_U0_C_7_we0),
    .C_7_d0(qwen_linear_layer_U0_C_7_d0),
    .C_7_address1(qwen_linear_layer_U0_C_7_address1),
    .C_7_ce1(qwen_linear_layer_U0_C_7_ce1),
    .C_7_we1(qwen_linear_layer_U0_C_7_we1),
    .C_7_d1(qwen_linear_layer_U0_C_7_d1),
    .C_8_address0(qwen_linear_layer_U0_C_8_address0),
    .C_8_ce0(qwen_linear_layer_U0_C_8_ce0),
    .C_8_we0(qwen_linear_layer_U0_C_8_we0),
    .C_8_d0(qwen_linear_layer_U0_C_8_d0),
    .C_8_address1(qwen_linear_layer_U0_C_8_address1),
    .C_8_ce1(qwen_linear_layer_U0_C_8_ce1),
    .C_8_we1(qwen_linear_layer_U0_C_8_we1),
    .C_8_d1(qwen_linear_layer_U0_C_8_d1),
    .C_9_address0(qwen_linear_layer_U0_C_9_address0),
    .C_9_ce0(qwen_linear_layer_U0_C_9_ce0),
    .C_9_we0(qwen_linear_layer_U0_C_9_we0),
    .C_9_d0(qwen_linear_layer_U0_C_9_d0),
    .C_9_address1(qwen_linear_layer_U0_C_9_address1),
    .C_9_ce1(qwen_linear_layer_U0_C_9_ce1),
    .C_9_we1(qwen_linear_layer_U0_C_9_we1),
    .C_9_d1(qwen_linear_layer_U0_C_9_d1),
    .C_10_address0(qwen_linear_layer_U0_C_10_address0),
    .C_10_ce0(qwen_linear_layer_U0_C_10_ce0),
    .C_10_we0(qwen_linear_layer_U0_C_10_we0),
    .C_10_d0(qwen_linear_layer_U0_C_10_d0),
    .C_10_address1(qwen_linear_layer_U0_C_10_address1),
    .C_10_ce1(qwen_linear_layer_U0_C_10_ce1),
    .C_10_we1(qwen_linear_layer_U0_C_10_we1),
    .C_10_d1(qwen_linear_layer_U0_C_10_d1),
    .C_11_address0(qwen_linear_layer_U0_C_11_address0),
    .C_11_ce0(qwen_linear_layer_U0_C_11_ce0),
    .C_11_we0(qwen_linear_layer_U0_C_11_we0),
    .C_11_d0(qwen_linear_layer_U0_C_11_d0),
    .C_11_address1(qwen_linear_layer_U0_C_11_address1),
    .C_11_ce1(qwen_linear_layer_U0_C_11_ce1),
    .C_11_we1(qwen_linear_layer_U0_C_11_we1),
    .C_11_d1(qwen_linear_layer_U0_C_11_d1),
    .C_12_address0(qwen_linear_layer_U0_C_12_address0),
    .C_12_ce0(qwen_linear_layer_U0_C_12_ce0),
    .C_12_we0(qwen_linear_layer_U0_C_12_we0),
    .C_12_d0(qwen_linear_layer_U0_C_12_d0),
    .C_12_address1(qwen_linear_layer_U0_C_12_address1),
    .C_12_ce1(qwen_linear_layer_U0_C_12_ce1),
    .C_12_we1(qwen_linear_layer_U0_C_12_we1),
    .C_12_d1(qwen_linear_layer_U0_C_12_d1),
    .C_13_address0(qwen_linear_layer_U0_C_13_address0),
    .C_13_ce0(qwen_linear_layer_U0_C_13_ce0),
    .C_13_we0(qwen_linear_layer_U0_C_13_we0),
    .C_13_d0(qwen_linear_layer_U0_C_13_d0),
    .C_13_address1(qwen_linear_layer_U0_C_13_address1),
    .C_13_ce1(qwen_linear_layer_U0_C_13_ce1),
    .C_13_we1(qwen_linear_layer_U0_C_13_we1),
    .C_13_d1(qwen_linear_layer_U0_C_13_d1),
    .C_14_address0(qwen_linear_layer_U0_C_14_address0),
    .C_14_ce0(qwen_linear_layer_U0_C_14_ce0),
    .C_14_we0(qwen_linear_layer_U0_C_14_we0),
    .C_14_d0(qwen_linear_layer_U0_C_14_d0),
    .C_14_address1(qwen_linear_layer_U0_C_14_address1),
    .C_14_ce1(qwen_linear_layer_U0_C_14_ce1),
    .C_14_we1(qwen_linear_layer_U0_C_14_we1),
    .C_14_d1(qwen_linear_layer_U0_C_14_d1),
    .C_15_address0(qwen_linear_layer_U0_C_15_address0),
    .C_15_ce0(qwen_linear_layer_U0_C_15_ce0),
    .C_15_we0(qwen_linear_layer_U0_C_15_we0),
    .C_15_d0(qwen_linear_layer_U0_C_15_d0),
    .C_15_address1(qwen_linear_layer_U0_C_15_address1),
    .C_15_ce1(qwen_linear_layer_U0_C_15_ce1),
    .C_15_we1(qwen_linear_layer_U0_C_15_we1),
    .C_15_d1(qwen_linear_layer_U0_C_15_d1),
    .M(M),
    .N(N_W1),
    .K(K)
);

qwen_superblock_qwen_linear_layer_1 qwen_linear_layer_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(qwen_linear_layer_1_U0_ap_start),
    .ap_done(qwen_linear_layer_1_U0_ap_done),
    .ap_continue(qwen_linear_layer_1_U0_ap_continue),
    .ap_idle(qwen_linear_layer_1_U0_ap_idle),
    .ap_ready(qwen_linear_layer_1_U0_ap_ready),
    .A_0_address0(qwen_linear_layer_1_U0_A_0_address0),
    .A_0_ce0(qwen_linear_layer_1_U0_A_0_ce0),
    .A_0_q0(temp_t_q0),
    .A_0_address1(qwen_linear_layer_1_U0_A_0_address1),
    .A_0_ce1(qwen_linear_layer_1_U0_A_0_ce1),
    .A_0_q1(temp_t_q1),
    .A_1_address0(qwen_linear_layer_1_U0_A_1_address0),
    .A_1_ce0(qwen_linear_layer_1_U0_A_1_ce0),
    .A_1_q0(temp_1_t_q0),
    .A_1_address1(qwen_linear_layer_1_U0_A_1_address1),
    .A_1_ce1(qwen_linear_layer_1_U0_A_1_ce1),
    .A_1_q1(temp_1_t_q1),
    .A_2_address0(qwen_linear_layer_1_U0_A_2_address0),
    .A_2_ce0(qwen_linear_layer_1_U0_A_2_ce0),
    .A_2_q0(temp_2_t_q0),
    .A_2_address1(qwen_linear_layer_1_U0_A_2_address1),
    .A_2_ce1(qwen_linear_layer_1_U0_A_2_ce1),
    .A_2_q1(temp_2_t_q1),
    .A_3_address0(qwen_linear_layer_1_U0_A_3_address0),
    .A_3_ce0(qwen_linear_layer_1_U0_A_3_ce0),
    .A_3_q0(temp_3_t_q0),
    .A_3_address1(qwen_linear_layer_1_U0_A_3_address1),
    .A_3_ce1(qwen_linear_layer_1_U0_A_3_ce1),
    .A_3_q1(temp_3_t_q1),
    .A_4_address0(qwen_linear_layer_1_U0_A_4_address0),
    .A_4_ce0(qwen_linear_layer_1_U0_A_4_ce0),
    .A_4_q0(temp_4_t_q0),
    .A_4_address1(qwen_linear_layer_1_U0_A_4_address1),
    .A_4_ce1(qwen_linear_layer_1_U0_A_4_ce1),
    .A_4_q1(temp_4_t_q1),
    .A_5_address0(qwen_linear_layer_1_U0_A_5_address0),
    .A_5_ce0(qwen_linear_layer_1_U0_A_5_ce0),
    .A_5_q0(temp_5_t_q0),
    .A_5_address1(qwen_linear_layer_1_U0_A_5_address1),
    .A_5_ce1(qwen_linear_layer_1_U0_A_5_ce1),
    .A_5_q1(temp_5_t_q1),
    .A_6_address0(qwen_linear_layer_1_U0_A_6_address0),
    .A_6_ce0(qwen_linear_layer_1_U0_A_6_ce0),
    .A_6_q0(temp_6_t_q0),
    .A_6_address1(qwen_linear_layer_1_U0_A_6_address1),
    .A_6_ce1(qwen_linear_layer_1_U0_A_6_ce1),
    .A_6_q1(temp_6_t_q1),
    .A_7_address0(qwen_linear_layer_1_U0_A_7_address0),
    .A_7_ce0(qwen_linear_layer_1_U0_A_7_ce0),
    .A_7_q0(temp_7_t_q0),
    .A_7_address1(qwen_linear_layer_1_U0_A_7_address1),
    .A_7_ce1(qwen_linear_layer_1_U0_A_7_ce1),
    .A_7_q1(temp_7_t_q1),
    .A_8_address0(qwen_linear_layer_1_U0_A_8_address0),
    .A_8_ce0(qwen_linear_layer_1_U0_A_8_ce0),
    .A_8_q0(temp_8_t_q0),
    .A_8_address1(qwen_linear_layer_1_U0_A_8_address1),
    .A_8_ce1(qwen_linear_layer_1_U0_A_8_ce1),
    .A_8_q1(temp_8_t_q1),
    .A_9_address0(qwen_linear_layer_1_U0_A_9_address0),
    .A_9_ce0(qwen_linear_layer_1_U0_A_9_ce0),
    .A_9_q0(temp_9_t_q0),
    .A_9_address1(qwen_linear_layer_1_U0_A_9_address1),
    .A_9_ce1(qwen_linear_layer_1_U0_A_9_ce1),
    .A_9_q1(temp_9_t_q1),
    .A_10_address0(qwen_linear_layer_1_U0_A_10_address0),
    .A_10_ce0(qwen_linear_layer_1_U0_A_10_ce0),
    .A_10_q0(temp_10_t_q0),
    .A_10_address1(qwen_linear_layer_1_U0_A_10_address1),
    .A_10_ce1(qwen_linear_layer_1_U0_A_10_ce1),
    .A_10_q1(temp_10_t_q1),
    .A_11_address0(qwen_linear_layer_1_U0_A_11_address0),
    .A_11_ce0(qwen_linear_layer_1_U0_A_11_ce0),
    .A_11_q0(temp_11_t_q0),
    .A_11_address1(qwen_linear_layer_1_U0_A_11_address1),
    .A_11_ce1(qwen_linear_layer_1_U0_A_11_ce1),
    .A_11_q1(temp_11_t_q1),
    .A_12_address0(qwen_linear_layer_1_U0_A_12_address0),
    .A_12_ce0(qwen_linear_layer_1_U0_A_12_ce0),
    .A_12_q0(temp_12_t_q0),
    .A_12_address1(qwen_linear_layer_1_U0_A_12_address1),
    .A_12_ce1(qwen_linear_layer_1_U0_A_12_ce1),
    .A_12_q1(temp_12_t_q1),
    .A_13_address0(qwen_linear_layer_1_U0_A_13_address0),
    .A_13_ce0(qwen_linear_layer_1_U0_A_13_ce0),
    .A_13_q0(temp_13_t_q0),
    .A_13_address1(qwen_linear_layer_1_U0_A_13_address1),
    .A_13_ce1(qwen_linear_layer_1_U0_A_13_ce1),
    .A_13_q1(temp_13_t_q1),
    .A_14_address0(qwen_linear_layer_1_U0_A_14_address0),
    .A_14_ce0(qwen_linear_layer_1_U0_A_14_ce0),
    .A_14_q0(temp_14_t_q0),
    .A_14_address1(qwen_linear_layer_1_U0_A_14_address1),
    .A_14_ce1(qwen_linear_layer_1_U0_A_14_ce1),
    .A_14_q1(temp_14_t_q1),
    .A_15_address0(qwen_linear_layer_1_U0_A_15_address0),
    .A_15_ce0(qwen_linear_layer_1_U0_A_15_ce0),
    .A_15_q0(temp_15_t_q0),
    .A_15_address1(qwen_linear_layer_1_U0_A_15_address1),
    .A_15_ce1(qwen_linear_layer_1_U0_A_15_ce1),
    .A_15_q1(temp_15_t_q1),
    .m_axi_gmem2_0_AWVALID(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWVALID),
    .m_axi_gmem2_0_AWREADY(1'b0),
    .m_axi_gmem2_0_AWADDR(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWADDR),
    .m_axi_gmem2_0_AWID(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWID),
    .m_axi_gmem2_0_AWLEN(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWLEN),
    .m_axi_gmem2_0_AWSIZE(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWSIZE),
    .m_axi_gmem2_0_AWBURST(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWBURST),
    .m_axi_gmem2_0_AWLOCK(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWLOCK),
    .m_axi_gmem2_0_AWCACHE(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWCACHE),
    .m_axi_gmem2_0_AWPROT(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWPROT),
    .m_axi_gmem2_0_AWQOS(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWQOS),
    .m_axi_gmem2_0_AWREGION(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWREGION),
    .m_axi_gmem2_0_AWUSER(qwen_linear_layer_1_U0_m_axi_gmem2_0_AWUSER),
    .m_axi_gmem2_0_WVALID(qwen_linear_layer_1_U0_m_axi_gmem2_0_WVALID),
    .m_axi_gmem2_0_WREADY(1'b0),
    .m_axi_gmem2_0_WDATA(qwen_linear_layer_1_U0_m_axi_gmem2_0_WDATA),
    .m_axi_gmem2_0_WSTRB(qwen_linear_layer_1_U0_m_axi_gmem2_0_WSTRB),
    .m_axi_gmem2_0_WLAST(qwen_linear_layer_1_U0_m_axi_gmem2_0_WLAST),
    .m_axi_gmem2_0_WID(qwen_linear_layer_1_U0_m_axi_gmem2_0_WID),
    .m_axi_gmem2_0_WUSER(qwen_linear_layer_1_U0_m_axi_gmem2_0_WUSER),
    .m_axi_gmem2_0_ARVALID(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARVALID),
    .m_axi_gmem2_0_ARREADY(gmem2_0_ARREADY),
    .m_axi_gmem2_0_ARADDR(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARADDR),
    .m_axi_gmem2_0_ARID(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARID),
    .m_axi_gmem2_0_ARLEN(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARLEN),
    .m_axi_gmem2_0_ARSIZE(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARSIZE),
    .m_axi_gmem2_0_ARBURST(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARBURST),
    .m_axi_gmem2_0_ARLOCK(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARLOCK),
    .m_axi_gmem2_0_ARCACHE(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARCACHE),
    .m_axi_gmem2_0_ARPROT(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARPROT),
    .m_axi_gmem2_0_ARQOS(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARQOS),
    .m_axi_gmem2_0_ARREGION(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARREGION),
    .m_axi_gmem2_0_ARUSER(qwen_linear_layer_1_U0_m_axi_gmem2_0_ARUSER),
    .m_axi_gmem2_0_RVALID(gmem2_0_RVALID),
    .m_axi_gmem2_0_RREADY(qwen_linear_layer_1_U0_m_axi_gmem2_0_RREADY),
    .m_axi_gmem2_0_RDATA(gmem2_0_RDATA),
    .m_axi_gmem2_0_RLAST(gmem2_0_RLAST),
    .m_axi_gmem2_0_RID(gmem2_0_RID),
    .m_axi_gmem2_0_RFIFONUM(gmem2_0_RFIFONUM),
    .m_axi_gmem2_0_RUSER(gmem2_0_RUSER),
    .m_axi_gmem2_0_RRESP(gmem2_0_RRESP),
    .m_axi_gmem2_0_BVALID(1'b0),
    .m_axi_gmem2_0_BREADY(qwen_linear_layer_1_U0_m_axi_gmem2_0_BREADY),
    .m_axi_gmem2_0_BRESP(2'd0),
    .m_axi_gmem2_0_BID(1'd0),
    .m_axi_gmem2_0_BUSER(1'd0),
    .W(W2),
    .m_axi_gmem0_0_AWVALID(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWVALID),
    .m_axi_gmem0_0_AWREADY(gmem0_0_AWREADY),
    .m_axi_gmem0_0_AWADDR(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWADDR),
    .m_axi_gmem0_0_AWID(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWID),
    .m_axi_gmem0_0_AWLEN(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWLEN),
    .m_axi_gmem0_0_AWSIZE(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWSIZE),
    .m_axi_gmem0_0_AWBURST(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWBURST),
    .m_axi_gmem0_0_AWLOCK(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWLOCK),
    .m_axi_gmem0_0_AWCACHE(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWCACHE),
    .m_axi_gmem0_0_AWPROT(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWPROT),
    .m_axi_gmem0_0_AWQOS(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWQOS),
    .m_axi_gmem0_0_AWREGION(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWREGION),
    .m_axi_gmem0_0_AWUSER(qwen_linear_layer_1_U0_m_axi_gmem0_0_AWUSER),
    .m_axi_gmem0_0_WVALID(qwen_linear_layer_1_U0_m_axi_gmem0_0_WVALID),
    .m_axi_gmem0_0_WREADY(gmem0_0_WREADY),
    .m_axi_gmem0_0_WDATA(qwen_linear_layer_1_U0_m_axi_gmem0_0_WDATA),
    .m_axi_gmem0_0_WSTRB(qwen_linear_layer_1_U0_m_axi_gmem0_0_WSTRB),
    .m_axi_gmem0_0_WLAST(qwen_linear_layer_1_U0_m_axi_gmem0_0_WLAST),
    .m_axi_gmem0_0_WID(qwen_linear_layer_1_U0_m_axi_gmem0_0_WID),
    .m_axi_gmem0_0_WUSER(qwen_linear_layer_1_U0_m_axi_gmem0_0_WUSER),
    .m_axi_gmem0_0_ARVALID(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARVALID),
    .m_axi_gmem0_0_ARREADY(1'b0),
    .m_axi_gmem0_0_ARADDR(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARADDR),
    .m_axi_gmem0_0_ARID(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARID),
    .m_axi_gmem0_0_ARLEN(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARLEN),
    .m_axi_gmem0_0_ARSIZE(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARSIZE),
    .m_axi_gmem0_0_ARBURST(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARBURST),
    .m_axi_gmem0_0_ARLOCK(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARLOCK),
    .m_axi_gmem0_0_ARCACHE(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARCACHE),
    .m_axi_gmem0_0_ARPROT(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARPROT),
    .m_axi_gmem0_0_ARQOS(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARQOS),
    .m_axi_gmem0_0_ARREGION(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARREGION),
    .m_axi_gmem0_0_ARUSER(qwen_linear_layer_1_U0_m_axi_gmem0_0_ARUSER),
    .m_axi_gmem0_0_RVALID(1'b0),
    .m_axi_gmem0_0_RREADY(qwen_linear_layer_1_U0_m_axi_gmem0_0_RREADY),
    .m_axi_gmem0_0_RDATA(16'd0),
    .m_axi_gmem0_0_RLAST(1'b0),
    .m_axi_gmem0_0_RID(1'd0),
    .m_axi_gmem0_0_RFIFONUM(10'd0),
    .m_axi_gmem0_0_RUSER(1'd0),
    .m_axi_gmem0_0_RRESP(2'd0),
    .m_axi_gmem0_0_BVALID(gmem0_0_BVALID),
    .m_axi_gmem0_0_BREADY(qwen_linear_layer_1_U0_m_axi_gmem0_0_BREADY),
    .m_axi_gmem0_0_BRESP(gmem0_0_BRESP),
    .m_axi_gmem0_0_BID(gmem0_0_BID),
    .m_axi_gmem0_0_BUSER(gmem0_0_BUSER),
    .C(C),
    .M(M),
    .N(N_W2),
    .K(N_W1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_temp_15 <= 1'b0;
    end else begin
        if (((qwen_linear_layer_U0_ap_done & qwen_linear_layer_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_temp_15 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_temp_15 <= ap_sync_channel_write_temp_15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_qwen_linear_layer_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_qwen_linear_layer_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_qwen_linear_layer_1_U0_ap_ready <= ap_sync_qwen_linear_layer_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_qwen_linear_layer_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_qwen_linear_layer_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_qwen_linear_layer_U0_ap_ready <= ap_sync_qwen_linear_layer_U0_ap_ready;
        end
    end
end

assign ap_channel_done_temp_15 = (qwen_linear_layer_U0_ap_done & (ap_sync_reg_channel_write_temp_15 ^ 1'b1));

assign ap_done = qwen_linear_layer_1_U0_ap_done;

assign ap_idle = (qwen_linear_layer_U0_ap_idle & qwen_linear_layer_1_U0_ap_idle & (temp_15_t_empty_n ^ 1'b1));

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_temp_15 = ((qwen_linear_layer_U0_C_15_full_n & ap_channel_done_temp_15) | ap_sync_reg_channel_write_temp_15);

assign ap_sync_qwen_linear_layer_1_U0_ap_ready = (qwen_linear_layer_1_U0_ap_ready | ap_sync_reg_qwen_linear_layer_1_U0_ap_ready);

assign ap_sync_qwen_linear_layer_U0_ap_ready = (qwen_linear_layer_U0_ap_ready | ap_sync_reg_qwen_linear_layer_U0_ap_ready);

assign ap_sync_ready = (ap_sync_qwen_linear_layer_U0_ap_ready & ap_sync_qwen_linear_layer_1_U0_ap_ready);

assign gmem0_0_BID = 1'd0;

assign gmem0_0_BRESP = 2'd0;

assign gmem0_0_BUSER = 1'd0;

assign gmem0_0_RID = 1'd0;

assign gmem0_0_RLAST = 1'b0;

assign gmem0_0_RRESP = 2'd0;

assign gmem0_0_RUSER = 1'd0;

assign gmem1_0_RID = 1'd0;

assign gmem1_0_RLAST = 1'b0;

assign gmem1_0_RRESP = 2'd0;

assign gmem1_0_RUSER = 1'd0;

assign gmem2_0_RID = 1'd0;

assign gmem2_0_RLAST = 1'b0;

assign gmem2_0_RRESP = 2'd0;

assign gmem2_0_RUSER = 1'd0;

assign qwen_linear_layer_1_U0_ap_continue = 1'b1;

assign qwen_linear_layer_1_U0_ap_start = (temp_15_t_empty_n & (ap_sync_reg_qwen_linear_layer_1_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign qwen_linear_layer_U0_C_15_full_n = temp_15_i_full_n;

assign qwen_linear_layer_U0_ap_continue = ap_sync_channel_write_temp_15;

assign qwen_linear_layer_U0_ap_start = ((ap_sync_reg_qwen_linear_layer_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

endmodule //qwen_superblock
