[hls]
relative_roots=C:/Users/Brandon/Desktop/codes/hls_bruh/hls_component
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=qwen_linear_layer/VITIS_LOOP_250_3 
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=qwen_linear_layer.1/VITIS_LOOP_269_9  
syn.directive.loop_flatten=qwen_linear_layer.1/VITIS_LOOP_268_8  
syn.directive.array_partition=qwen_superblock/temp dim=1 type=cyclic factor=16 variable=temp


